version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: hw12
      POSTGRES_USER: university
      POSTGRES_PASSWORD: university
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
