"""removed contacts constraint

Revision ID: a2d9bff87125
Revises: fa5321c95e24
Create Date: 2025-03-23 11:12:02.184866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d9bff87125'
down_revision: Union[str, None] = 'fa5321c95e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_email_key', 'contacts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contacts_email_key', 'contacts', ['email'])
    # ### end Alembic commands ###
